#help from https://www.youtube.com/watch?v=KxqlJblhzfI
#help from https://stackoverflow.com/questions/25930191/connect-mysql-to-spring-application, https://spring.io/guides/gs/accessing-data-mysql/
server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt_security
    driver-class: com.mysql.cj.jdbc.Driver
    username: root
    password: admin123
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect